//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fruits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fruits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Game.Fruits", typeof(Fruits).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BET.
        /// </summary>
        public static string TEXT_BET {
            get {
                return ResourceManager.GetString("TEXT_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COIN.
        /// </summary>
        public static string TEXT_COIN {
            get {
                return ResourceManager.GetString("TEXT_COIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS.
        /// </summary>
        public static string TEXT_CONGRATS {
            get {
                return ResourceManager.GetString("TEXT_CONGRATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER.
        /// </summary>
        public static string TEXT_GAMEOVER {
            get {
                return ResourceManager.GetString("TEXT_GAMEOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS SIMBOL IS A JOLLY WHICH CAN REPLACE ANY OTHER SYMBOL TO MAKE UP A COMBO.
        /// </summary>
        public static string TEXT_HELP_WILD {
            get {
                return ResourceManager.GetString("TEXT_HELP_WILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string TEXT_INFO {
            get {
                return ResourceManager.GetString("TEXT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINES.
        /// </summary>
        public static string TEXT_LINES {
            get {
                return ResourceManager.GetString("TEXT_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX BET.
        /// </summary>
        public static string TEXT_MAX_BET {
            get {
                return ResourceManager.GetString("TEXT_MAX_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY.
        /// </summary>
        public static string TEXT_MONEY {
            get {
                return ResourceManager.GetString("TEXT_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string TEXT_PLAY {
            get {
                return ResourceManager.GetString("TEXT_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200x200.jpg.
        /// </summary>
        public static string TEXT_SHARE_IMAGE {
            get {
                return ResourceManager.GetString("TEXT_SHARE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You collected &lt;strong&gt;.
        /// </summary>
        public static string TEXT_SHARE_MSG1 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points&lt;/strong&gt;!&lt;br&gt;&lt;br&gt;Share your score with your friends!.
        /// </summary>
        public static string TEXT_SHARE_MSG2 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My score is .
        /// </summary>
        public static string TEXT_SHARE_SHARE1 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_SHARE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points! Can you do better?.
        /// </summary>
        public static string TEXT_SHARE_SHARE2 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_SHARE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string TEXT_SHARE_TITLE {
            get {
                return ResourceManager.GetString("TEXT_SHARE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPIN.
        /// </summary>
        public static string TEXT_SPIN {
            get {
                return ResourceManager.GetString("TEXT_SPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN.
        /// </summary>
        public static string TEXT_WIN {
            get {
                return ResourceManager.GetString("TEXT_WIN", resourceCulture);
            }
        }
    }
}
