//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Keno {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keno() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Game.Keno", typeof(Keno).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string TEXT_CLEAR {
            get {
                return ResourceManager.GetString("TEXT_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string TEXT_CONGRATULATIONS {
            get {
                return ResourceManager.GetString("TEXT_CONGRATULATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string TEXT_CURRENCY {
            get {
                return ResourceManager.GetString("TEXT_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU LOST YOUR CREDITS.
        /// </summary>
        public static string TEXT_GAMEOVER {
            get {
                return ResourceManager.GetString("TEXT_GAMEOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HITS.
        /// </summary>
        public static string TEXT_HITS {
            get {
                return ResourceManager.GetString("TEXT_HITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string TEXT_MIN {
            get {
                return ResourceManager.GetString("TEXT_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYOUTS.
        /// </summary>
        public static string TEXT_PAYOUTS {
            get {
                return ResourceManager.GetString("TEXT_PAYOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYS.
        /// </summary>
        public static string TEXT_PAYS {
            get {
                return ResourceManager.GetString("TEXT_PAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY ONE.
        /// </summary>
        public static string TEXT_PLAY1 {
            get {
                return ResourceManager.GetString("TEXT_PLAY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY FIVE.
        /// </summary>
        public static string TEXT_PLAY5 {
            get {
                return ResourceManager.GetString("TEXT_PLAY5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string TEXT_PLUS {
            get {
                return ResourceManager.GetString("TEXT_PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You collected &lt;strong&gt;.
        /// </summary>
        public static string TEXT_SHARE_1 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points&lt;/strong&gt;!&lt;br&gt;&lt;br&gt;Share your score with your friends!.
        /// </summary>
        public static string TEXT_SHARE_2 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My score is .
        /// </summary>
        public static string TEXT_SHARE_3 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points! Can you do better?.
        /// </summary>
        public static string TEXT_SHARE_4 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDO.
        /// </summary>
        public static string TEXT_UNDO {
            get {
                return ResourceManager.GetString("TEXT_UNDO", resourceCulture);
            }
        }
    }
}
