//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Poker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Poker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Game.Poker", typeof(Poker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BET.
        /// </summary>
        public static string TEXT_BET {
            get {
                return ResourceManager.GetString("TEXT_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BET ONE.
        /// </summary>
        public static string TEXT_BET_ONE {
            get {
                return ResourceManager.GetString("TEXT_BET_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE A CARD!.
        /// </summary>
        public static string TEXT_CHOOSE_CARD {
            get {
                return ResourceManager.GetString("TEXT_CHOOSE_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLLECT.
        /// </summary>
        public static string TEXT_COLLECT {
            get {
                return ResourceManager.GetString("TEXT_COLLECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Royal Flush|5 of a Kind|Royal Flush|Straight Flush|Four of a Kind|Full House|Flush|Straight|Three of a Kind|Two Pair|Kings or Better.
        /// </summary>
        public static string TEXT_COMBO {
            get {
                return ResourceManager.GetString("TEXT_COMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string TEXT_CONGRATULATIONS {
            get {
                return ResourceManager.GetString("TEXT_CONGRATULATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TEXT_CREDITS_DEVELOPED {
            get {
                return ResourceManager.GetString("TEXT_CREDITS_DEVELOPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string TEXT_CURRENCY {
            get {
                return ResourceManager.GetString("TEXT_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEAL.
        /// </summary>
        public static string TEXT_DEAL {
            get {
                return ResourceManager.GetString("TEXT_DEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEALER CARD.
        /// </summary>
        public static string TEXT_DEALER_CARD {
            get {
                return ResourceManager.GetString("TEXT_DEALER_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOUBLE.
        /// </summary>
        public static string TEXT_DOUBLE {
            get {
                return ResourceManager.GetString("TEXT_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOUBLE HALF.
        /// </summary>
        public static string TEXT_DOUBLE_HALF {
            get {
                return ResourceManager.GetString("TEXT_DOUBLE_HALF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOBLAR MITAD DE.
        /// </summary>
        public static string TEXT_DOUBLE_HALF_TO {
            get {
                return ResourceManager.GetString("TEXT_DOUBLE_HALF_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOUBLE UP TO.
        /// </summary>
        public static string TEXT_DOUBLE_UP {
            get {
                return ResourceManager.GetString("TEXT_DOUBLE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOUBLE HALF TO.
        /// </summary>
        public static string TEXT_DOUBLEUP_TO {
            get {
                return ResourceManager.GetString("TEXT_DOUBLEUP_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAW.
        /// </summary>
        public static string TEXT_DRAW {
            get {
                return ResourceManager.GetString("TEXT_DRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string TEXT_EXIT {
            get {
                return ResourceManager.GetString("TEXT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BET MAX.
        /// </summary>
        public static string TEXT_MAX_BET {
            get {
                return ResourceManager.GetString("TEXT_MAX_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY.
        /// </summary>
        public static string TEXT_MONEY {
            get {
                return ResourceManager.GetString("TEXT_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ENOUGH MONEY.
        /// </summary>
        public static string TEXT_NO_MONEY {
            get {
                return ResourceManager.GetString("TEXT_NO_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO WIN.
        /// </summary>
        public static string TEXT_NO_WIN {
            get {
                return ResourceManager.GetString("TEXT_NO_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string TEXT_PLAY {
            get {
                return ResourceManager.GetString("TEXT_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECHARGE.
        /// </summary>
        public static string TEXT_RECHARGE {
            get {
                return ResourceManager.GetString("TEXT_RECHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You collected &lt;strong&gt;.
        /// </summary>
        public static string TEXT_SHARE_1 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;points&lt;/strong&gt;!&lt;br&gt;&lt;br&gt;Share your score with your friends!.
        /// </summary>
        public static string TEXT_SHARE_2 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My score is&amp;nbsp;.
        /// </summary>
        public static string TEXT_SHARE_3 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;points! Can you do better?.
        /// </summary>
        public static string TEXT_SHARE_4 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN.
        /// </summary>
        public static string TEXT_WIN {
            get {
                return ResourceManager.GetString("TEXT_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU LOSE.
        /// </summary>
        public static string TEXT_YOU_LOSE {
            get {
                return ResourceManager.GetString("TEXT_YOU_LOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WON.
        /// </summary>
        public static string TEXT_YOU_WON {
            get {
                return ResourceManager.GetString("TEXT_YOU_WON", resourceCulture);
            }
        }
    }
}
