//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Racing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Racing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Game.Racing", typeof(Racing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL YOUR BETS WILL BE LOST!! ARE YOU SURE?.
        /// </summary>
        public static string TEXT_ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("TEXT_ARE_YOU_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BET.
        /// </summary>
        public static string TEXT_BET {
            get {
                return ResourceManager.GetString("TEXT_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR BET.
        /// </summary>
        public static string TEXT_CLEAR_BET {
            get {
                return ResourceManager.GetString("TEXT_CLEAR_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TEXT_CREDITS_DEVELOPED {
            get {
                return ResourceManager.GetString("TEXT_CREDITS_DEVELOPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string TEXT_CURRENCY {
            get {
                return ResourceManager.GetString("TEXT_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR BET IS HIGHER THAN MAXIMUM ONE!!.
        /// </summary>
        public static string TEXT_ERR_MAX_BET {
            get {
                return ResourceManager.GetString("TEXT_ERR_MAX_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR BET IS LOWER THAN MINIMUM ONE!!.
        /// </summary>
        public static string TEXT_ERR_MIN_BET {
            get {
                return ResourceManager.GetString("TEXT_ERR_MIN_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREYHOUND NAME.
        /// </summary>
        public static string TEXT_GREYHOUND_NAME {
            get {
                return ResourceManager.GetString("TEXT_GREYHOUND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX BET.
        /// </summary>
        public static string TEXT_MAX_BET {
            get {
                return ResourceManager.GetString("TEXT_MAX_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN BET.
        /// </summary>
        public static string TEXT_MIN_BET {
            get {
                return ResourceManager.GetString("TEXT_MIN_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY.
        /// </summary>
        public static string TEXT_MONEY {
            get {
                return ResourceManager.GetString("TEXT_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ENOUGH MONEY!!.
        /// </summary>
        public static string TEXT_NO_MONEY {
            get {
                return ResourceManager.GetString("TEXT_NO_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO WIN.
        /// </summary>
        public static string TEXT_NO_WIN {
            get {
                return ResourceManager.GetString("TEXT_NO_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODDS.
        /// </summary>
        public static string TEXT_ODDS {
            get {
                return ResourceManager.GetString("TEXT_ODDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACE.
        /// </summary>
        public static string TEXT_PLACE {
            get {
                return ResourceManager.GetString("TEXT_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200x200.jpg.
        /// </summary>
        public static string TEXT_SHARE_IMAGE {
            get {
                return ResourceManager.GetString("TEXT_SHARE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You collected &lt;strong&gt;.
        /// </summary>
        public static string TEXT_SHARE_MSG1 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;points&lt;/strong&gt;!&lt;br&gt;&lt;br&gt;Share your score with your friends!.
        /// </summary>
        public static string TEXT_SHARE_MSG2 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My score is&amp;nbsp;.
        /// </summary>
        public static string TEXT_SHARE_SHARE1 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_SHARE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;points! Can you do better.
        /// </summary>
        public static string TEXT_SHARE_SHARE2 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_SHARE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string TEXT_SHARE_TITLE {
            get {
                return ResourceManager.GetString("TEXT_SHARE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW.
        /// </summary>
        public static string TEXT_SHOW {
            get {
                return ResourceManager.GetString("TEXT_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START RACE.
        /// </summary>
        public static string TEXT_START_RACE {
            get {
                return ResourceManager.GetString("TEXT_START_RACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAP.
        /// </summary>
        public static string TEXT_TRAP {
            get {
                return ResourceManager.GetString("TEXT_TRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN.
        /// </summary>
        public static string TEXT_WIN {
            get {
                return ResourceManager.GetString("TEXT_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINS.
        /// </summary>
        public static string TEXT_WINS {
            get {
                return ResourceManager.GetString("TEXT_WINS", resourceCulture);
            }
        }
    }
}
