//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Roulette {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Roulette() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Game.Roulette", typeof(Roulette).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BET.
        /// </summary>
        public static string TEXT_BET {
            get {
                return ResourceManager.GetString("TEXT_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COIN.
        /// </summary>
        public static string TEXT_COIN {
            get {
                return ResourceManager.GetString("TEXT_COIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string TEXT_CONGRATULATIONS {
            get {
                return ResourceManager.GetString("TEXT_CONGRATULATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TEXT_CREDITS_DEVELOPED {
            get {
                return ResourceManager.GetString("TEXT_CREDITS_DEVELOPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUR BET.
        /// </summary>
        public static string TEXT_CUR_BET {
            get {
                return ResourceManager.GetString("TEXT_CUR_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string TEXT_CURRENCY {
            get {
                return ResourceManager.GetString("TEXT_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX BET REACHED!!.
        /// </summary>
        public static string TEXT_ERROR_MAX_BET_REACHED {
            get {
                return ResourceManager.GetString("TEXT_ERROR_MAX_BET_REACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU BET IS LOWER THAN MINIMUM BET!!.
        /// </summary>
        public static string TEXT_ERROR_MIN_BET {
            get {
                return ResourceManager.GetString("TEXT_ERROR_MIN_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ENOUGH MONEY FOR THIS BET!!.
        /// </summary>
        public static string TEXT_ERROR_NO_MONEY_MSG {
            get {
                return ResourceManager.GetString("TEXT_ERROR_NO_MONEY_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string TEXT_EXIT {
            get {
                return ResourceManager.GetString("TEXT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINALS BET.
        /// </summary>
        public static string TEXT_FINALSBET {
            get {
                return ResourceManager.GetString("TEXT_FINALSBET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY.
        /// </summary>
        public static string TEXT_HISTORY {
            get {
                return ResourceManager.GetString("TEXT_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TEXT_LINK {
            get {
                return ResourceManager.GetString("TEXT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX BET.
        /// </summary>
        public static string TEXT_MAX_BET {
            get {
                return ResourceManager.GetString("TEXT_MAX_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN BET.
        /// </summary>
        public static string TEXT_MIN_BET {
            get {
                return ResourceManager.GetString("TEXT_MIN_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY.
        /// </summary>
        public static string TEXT_MONEY {
            get {
                return ResourceManager.GetString("TEXT_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEIGHBORS.
        /// </summary>
        public static string TEXT_NEIGHBORS {
            get {
                return ResourceManager.GetString("TEXT_NEIGHBORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU DON&apos;T HAVE ENOUGH MONEY!!!.
        /// </summary>
        public static string TEXT_NO_MONEY {
            get {
                return ResourceManager.GetString("TEXT_NO_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORPHELINS.
        /// </summary>
        public static string TEXT_ORPHELINS {
            get {
                return ResourceManager.GetString("TEXT_ORPHELINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string TEXT_PLAY {
            get {
                return ResourceManager.GetString("TEXT_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBET.
        /// </summary>
        public static string TEXT_REBET {
            get {
                return ResourceManager.GetString("TEXT_REBET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECHARGE.
        /// </summary>
        public static string TEXT_RECHARGE {
            get {
                return ResourceManager.GetString("TEXT_RECHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE CLICK RECHARGE BUTTON TO PLAY AGAIN.
        /// </summary>
        public static string TEXT_RECHARGE_MSG {
            get {
                return ResourceManager.GetString("TEXT_RECHARGE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You collected &lt;strong&gt;.
        /// </summary>
        public static string TEXT_SHARE_1 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;points&lt;/strong&gt;!&lt;br&gt;&lt;br&gt;Share your score with your friends!.
        /// </summary>
        public static string TEXT_SHARE_2 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My score is&amp;nbsp;.
        /// </summary>
        public static string TEXT_SHARE_3 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;points! Can you do better?.
        /// </summary>
        public static string TEXT_SHARE_4 {
            get {
                return ResourceManager.GetString("TEXT_SHARE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPIN.
        /// </summary>
        public static string TEXT_SPIN {
            get {
                return ResourceManager.GetString("TEXT_SPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIER.
        /// </summary>
        public static string TEXT_TIER {
            get {
                return ResourceManager.GetString("TEXT_TIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOISINS DU ZERO.
        /// </summary>
        public static string TEXT_VOISINS_ZERO {
            get {
                return ResourceManager.GetString("TEXT_VOISINS_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN.
        /// </summary>
        public static string TEXT_WIN {
            get {
                return ResourceManager.GetString("TEXT_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU LOST.
        /// </summary>
        public static string TEXT_YOU_LOSE {
            get {
                return ResourceManager.GetString("TEXT_YOU_LOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WON.
        /// </summary>
        public static string TEXT_YOU_WIN {
            get {
                return ResourceManager.GetString("TEXT_YOU_WIN", resourceCulture);
            }
        }
    }
}
