//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Soccer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Soccer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Game.Soccer", typeof(Soccer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BET.
        /// </summary>
        public static string TEXT_BET {
            get {
                return ResourceManager.GetString("TEXT_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COIN.
        /// </summary>
        public static string TEXT_COIN {
            get {
                return ResourceManager.GetString("TEXT_COIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS!!.
        /// </summary>
        public static string TEXT_CONGRATS {
            get {
                return ResourceManager.GetString("TEXT_CONGRATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string TEXT_CONGRATULATIONS {
            get {
                return ResourceManager.GetString("TEXT_CONGRATULATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string TEXT_CURRENCY {
            get {
                return ResourceManager.GetString("TEXT_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TEXT_DEVELOPED {
            get {
                return ResourceManager.GetString("TEXT_DEVELOPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREESPINS.
        /// </summary>
        public static string TEXT_FREESPINS {
            get {
                return ResourceManager.GetString("TEXT_FREESPINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 OR MORE ON ANY REELS, WILL TRIGGER PENALTY KICK BONUS!!.
        /// </summary>
        public static string TEXT_HELP_BONUS1 {
            get {
                return ResourceManager.GetString("TEXT_HELP_BONUS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE WHERE TO KICK THE BALL TO GET A PRIZE!!.
        /// </summary>
        public static string TEXT_HELP_BONUS2 {
            get {
                return ResourceManager.GetString("TEXT_HELP_BONUS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET 3 OR MORE FREESPIN SYMBOL ON ANY REEL TO TRIGGER FREESPINS.
        /// </summary>
        public static string TEXT_HELP_FREESPIN {
            get {
                return ResourceManager.GetString("TEXT_HELP_FREESPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINES.
        /// </summary>
        public static string TEXT_LINES {
            get {
                return ResourceManager.GetString("TEXT_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX BET.
        /// </summary>
        public static string TEXT_MAX_BET {
            get {
                return ResourceManager.GetString("TEXT_MAX_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY.
        /// </summary>
        public static string TEXT_MONEY {
            get {
                return ResourceManager.GetString("TEXT_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You collected &lt;strong&gt;.
        /// </summary>
        public static string TEXT_MSG_SHARE1 {
            get {
                return ResourceManager.GetString("TEXT_MSG_SHARE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;points&lt;/strong&gt;!&lt;br&gt;&lt;br&gt;Share your score with your friends!.
        /// </summary>
        public static string TEXT_MSG_SHARE2 {
            get {
                return ResourceManager.GetString("TEXT_MSG_SHARE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My score is&amp;nbsp;.
        /// </summary>
        public static string TEXT_MSG_SHARING1 {
            get {
                return ResourceManager.GetString("TEXT_MSG_SHARING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;points! Can you do better?.
        /// </summary>
        public static string TEXT_MSG_SHARING2 {
            get {
                return ResourceManager.GetString("TEXT_MSG_SHARING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ENOUGH MONEY FOR MAX BET!!.
        /// </summary>
        public static string TEXT_NO_MAX_BET {
            get {
                return ResourceManager.GetString("TEXT_NO_MAX_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ENOUGH MONEY FOR THE CURRENT BET!.
        /// </summary>
        public static string TEXT_NOT_ENOUGH_MONEY {
            get {
                return ResourceManager.GetString("TEXT_NOT_ENOUGH_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYTABLE.
        /// </summary>
        public static string TEXT_PAYTABLE {
            get {
                return ResourceManager.GetString("TEXT_PAYTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN.
        /// </summary>
        public static string TEXT_WIN {
            get {
                return ResourceManager.GetString("TEXT_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WON.
        /// </summary>
        public static string TEXT_YOU_WIN {
            get {
                return ResourceManager.GetString("TEXT_YOU_WIN", resourceCulture);
            }
        }
    }
}
